### ISSUE TITLE
add OAPI doc for swagger via flask-restful-swagger

### ISSUE THREAD

**Issue by foreveremain** [warownia1/Slivka#32]
Looks fairly straightforward to have dynamic swagger docs generated for a configured Slivka instance via https://github.com/rantav/flask-restful-swagger

Wrinkles: service specific parameters/data types would need to be mapped to OAPI. We may also need to add additional metadata conformant with biotools to enable autodiscovery and indexing via the Elixir services registry (see e.g. http://www.biorxiv.org/content/biorxiv/early/2017/07/30/170274.full.pdf )

**Comment by warownia1** [comment]
Switching to flask-restful-swagger would require rewriting the entire module, and writing the REST documentation between the lines of code. Swagger docs are not quite auto generated, they require you embed swagger documentation syntax into the code obscuring it. I suggest putting the REST API documentation in the yaml file outside the code and generate api pages from it.
